### ISSUE TITLE
Code doesn't work on Three 152 and more

### ISSUE THREAD

**Issue by sbiaudet** [N8python/subsurfaceScatteringMat#1]
I've tried to use this material in a threejs project in version 152, and I'm getting errors compiling the shaders. I passed this repo to version 152 and I have the same errors. Could you help me ?

<img width="1488" alt="image" src="https://github.com/N8python/subsurfaceScatteringMat/assets/3100668/bade129e-93a2-4220-a9b4-df4b653464dd">

**Comment by N8python** [comment]
APIs change... this was kinda an experimental demo so I'd recommend looking through all the threejs glsl fragments and finding the corresponding function signature changes. This isn't officially maintained, but if you have any questions while doing so, I'd be happy to help.

**Comment by sbiaudet** [comment]
I think the community would appreciate a PBR material with subsurface scattering feature. Could you refactor the code and offer it as a sample on the official Three repo???

**Comment by N8python** [comment]
Updated to r152. Should work now. I posted it on twitter - there was little to no interest in it.
